services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-net
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/letsencrypt
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=batista.jonathas@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    networks:
      - traefik-net
    labels:
      # Dashboard UI (protected)
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-ui.rule=Host(`traefik.jonbatista.dev`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard-ui.service=api@internal"
      - "traefik.http.routers.dashboard-ui.entrypoints=websecure"
      - "traefik.http.routers.dashboard-ui.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard-ui.middlewares=dashboard-auth"

      # Dashboard API + static files (unprotected)
      - "traefik.http.routers.dashboard-api.rule=Host(`traefik.jonbatista.dev`) && (PathPrefix(`/api`) || PathPrefix(`/static`))"
      - "traefik.http.routers.dashboard-api.service=api@internal"
      - "traefik.http.routers.dashboard-api.entrypoints=websecure"
      - "traefik.http.routers.dashboard-api.tls.certresolver=myresolver"

      # Basic auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=jon:$apr1$/lTnmJLy$H3QCp4.1FfkLHUMeQ7ulm0"
networks:
  traefik-net:
    name: traefik-net

