apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.15.242
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
  ports:
    - port: 5432
      targetPort: 5432

